os: osx
osx_image: xcode8.3
sudo: false
language: objective-c

env:
  - NODE_VERSION="4"
  - NODE_VERSION="5"
  - NODE_VERSION="6"

licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'


before_install:
  - brew update > /dev/null
  - export ANDROID_HOME=/usr/local/opt/android-sdk
  - export PATH=$PATH:/usr/local/opt/android-sdk/tools:/usr/local/opt/android-sdk/platform-tools
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
  - source ~/.nvm/nvm.sh && nvm install $NODE_VERSION && nvm use $NODE_VERSION
  - PATH="`npm bin`:`npm bin -g`:$PATH"
#  - brew install android-sdk
#  - echo y | android update sdk --filter tools,platform-tools,android-23,build-tools-23.0.3,extra-android-m2repository,extra-google-m2repository,extra-android-support --all --no-ui;
  - npm install -g npm
  - npm install -g nativescript@rc
  # CocoaPods
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pod --version
  - pod setup --silent
  - pod repo update --silent
  # Show environment invo
  - node --version
  - npm --version
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks
  - echo $ANDROID_HOME

install:
    - tns usage-reporting disable
    - tns error-reporting disable
    - npm install

script:
  - export ANDROID_HOME=/usr/local/opt/android-sdk
  - export PATH=$PATH:/usr/local/opt/android-sdk/tools:/usr/local/opt/android-sdk/platform-tools
  - npm run build
  - npm run test
 # - npm run e2e